[telegram]
token = "2132560051:AAFSC1M5sepj82u2iD6NSpTwGPH5J_zrwbY"
workers = 1
admins = [1556000518]
admins_only = false
maintenance_mode = false
persistent_temp_data = true

[pyrogram]
enabled = false
api_id = 2677896
api_hash = "7f37813fa807d4df7ccd358218a25d51"

[sqlite]
filename = "stickersbot.sqlite"

[bot]
sourcecode = "t.me/DamienSoukara"
issues = "Github@AmineSoukara"
channel = "DamienSoukara"
